name: Govee to MQTT Bridge
# image: ghcr.io/wez/govee2mqtt-{arch}
version: "v0.0.1"
slug: govee2mqtt
description: Control Govee Devices
url: https://github.com/stefanovazzocell/govee2mqtt
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
services:
  - mqtt:need

apparmor: true

webui: http://[HOST]:[PORT:8056]/assets/index.html
#ingress: true
#ingress_port: 8056

# Host network access is required for LAN discovery
host_network: true

args:
  REPO_URL: https://github.com/stefanovazzocell/govee2mqtt
  REPO_REF: main

map:
  - type: addon_config
    read_only: false
    path: /app/config

options:
  temperature_scale: "C"

schema:
  temperature_scale: "str?"
  govee_email: "str?"
  govee_password: "password?"
  govee_api_key: "password?"
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_username: "str?"
  mqtt_password: "password?"
  debug_level: "str?"
  no_multicast: "bool?"
  broadcast_all: "bool?"
  global_broadcast: "bool?"
  scan: "str?"
